BYTES-TO-READ: 130
COMMANDS: true
DEBUG: true
DEV: 1
LOGGING: null
LOGGING-PATH-CLIENT: logs/client_logs.csv
LOGGING-PATH-RPI: logs/rpi_logs.csv
RPI-IP: 192.168.1.97
RPI-PORT: 9001
UART: /dev/ttyS0
UART-BAUD: 115200
VERSION: 0.2
