BYTES-PER-LINE: 130
COMMANDS: true
DEBUG: true
LOGGING: null
LOGGING-PATH-CLIENT: logs/client_logs.csv
LOGGING-PATH-RPI: logs/rpi_logs.csv
MAX-DEV: 1
RPI-IP: 192.168.1.72
RPI-PORT: 9001
UART: /dev/ttyS0
UART-BAUD: 115200
VERSION: 0.2
