BYTES-TO-READ: 130
COMMANDS: false
<<<<<<< HEAD
DEBUG: false
=======
DEBUG: true
>>>>>>> f4f94e052468eb5d2a298b131dd2ffaf3f7ce798
DEV: 1
LOGGING: null
LOGGING-PATH-CLIENT: logs/client_logs.csv
LOGGING-PATH-RPI: logs/rpi_logs.csv
RPI-IP: 192.168.1.83
RPI-PORT: 9001
UART: /dev/ttyS0
UART-BAUD: 115200
VERSION: 0.2
